### ISSUE TITLE
prototype map viewer

### ISSUE THREAD

**Issue by wilsaj** [TNRIS/flood#2]
To be available by May 1.

Needs to have a few live (near-realtime) data layers:
- [x] NOAA NWS gauges w/predictions and flood stages: #37
- [ ] ~~USGS NWIS streamflow gauges: #42~~
- [x]  Precipitation (Doppler): #39, #31
- [ ]  NWS Watches & Warnings: #40 
- [ ]  ~~Low-water crossing closures (from atxfloods.com): #41~~
- [x]  WaterDataForTexas reservoir current conditions: #38

**Comment by sashahart** [comment]
- [ ] NOAA NWS gauges w/predictions and flood stages: #37
- [ ]  USGS NWIS streamflow gauges: #42 
- [ ]  Precipitation (Doppler): #39, #31
- [ ]  NWS Watches & Warnings: #40 
- [ ]  Low-water crossing closures (from atxfloods.com): #41 
- [ ]  WaterDataForTexas reservoir current conditions: #38

**Comment by wilsaj** [comment]
Here's the very excellent mockup that @christoball put together:

![image](https://cloud.githubusercontent.com/assets/303866/14032178/111030fa-f1df-11e5-8084-a563e533bbc6.png)

**Comment by sashahart** [comment]
May 1 passed a long time ago and something like this is live. I don't think we need an issue for a prototype anymore, and all the bullet points except #40 are closed, so I'm closing this and someone can reopen it if it still means something.
