### ISSUE TITLE
Data Service

### ISSUE THREAD

**Issue by sashahart** [TNRIS/flood#70]
This issue splits out discussion of what others have called the data service. 

To rephrase what others have said (corrections welcome), the data service is a simple HTTP JSON API which the front end can use to get data about gauges, e.g.
-  "give me all the data at gauge from '2016-03-17' to now"
-  "give me all the streamflow gauges within bbox"

I believe these two queries imply certain capabilities
- [ ] Range queries on timestamps
- [ ] Bounding box queries, i.e. combining range queries on x and y coordinates

Data service should handle heavy, bursty read loads, and it should not go down very much. That defines these dependencies, partly concerning where the API itself runs but mostly the datastore:
- [ ] Load testing to explore and then demonstrate these properties #3
- [ ] Either provision capacity in advance, or set up some kind of autoscaling to manage capacity

**Comment by sashahart** [comment]
One idea I've had is that this can be written in Node. I'll offer a few reasons to consider but really, whatever. :)

Mostly, it will be pretty closely coupled with the frontend that consumes it, and it will be convenient for Javascript-oriented developers to tweak it if it's written in Javascript.

Also, my impression is that the Node SDK for DynamoDB is more fully-cooked than anything available for Python to do the same work. 

It could also serve as a mechanism for communicating to pipeline precisely what data service needs to do with DynamoDB, without having to answer a ton of dumb questions in email.

Also, obviously, I am trying to fob this work off on Andy, seeing as I am no expert with Node or spatial querying in Node - but it's not like I don't also have personal conviction about it.

**Comment by sashahart** [comment]
Previous plans were to use DynamoDB and it seems like a good choice for various reasons, so let's do that. 

This defines certain dependencies:
- [ ] Setting up DynamoDB with involved tables, involves #71
- [ ] Pipeline needs to push whatever Data Service needs to DynamoDB, also involves #71

**Comment by wilsaj** [comment]
I'm going to reframe and scale back the scope of the data service / API a bit. To keep things simple, it doesn't need to handle time series queries or anything spatial other than being able to contain x and y coordinates (longitude and latitude).
- the time periods we need to query are fixed, and are not very large (just recent values + a few days of predictions)
- we should be able to offload any spatial queries to CartoDB via their SQL API


For MVP, we really only have one API endpoint that we need to handle. We need to be able to query flood gauge by id and get enough information to recreate the hydrograph, as shown on the gauge pages http://water.weather.gov/ahps2/hydrograph.php?wfo=jan&gage=cogl1 - so that means:
- recently observed values (stage and streamflow)
- if a still-valid forecast has been issued, those predicted values
- flood stage elevations for the gauge


On the long and winding roadmap into the future, a few things have been floated:
- similar functionality for the USGS streamflow gauges (recreating hydrographs)
- road closure information
- representing weather stations (precip, windspeed, etc)


Another consideration: we *could* roll the serialization of backend -> geojson for the push-to-CartoDB service into this data API. That would mean adding a single endpoint for every CartoDB table that just queries backend (DynamoDB) and spits out a complete picture of the CartoDB table as geojson. The push-to-cartodb service would then compare old CartoDB state with this new state and send updates as needed. Maybe this is a good idea to help define a firm boundary between pipeline and push-to-cartodb service? We should talk about this.


What's been referred **a** data service may be easier to think of as multiple tiny layer-specific services.. a collection of API endpoints for which we don't yet have a complete picture. For example, road closures probably won't have anything that resembles data values or charts. We can't know exactly what all of our data sources will look like yet; they could very well end up coming to us in some weird and wonderful formats. So we should focus on getting what we have off of the ground, but expect and plan for change.


As far as implementation - I'll take ownership of that. I feel like our use case fits well with AWS [API gateway](https://aws.amazon.com/api-gateway/) + [lambda](https://aws.amazon.com/lambda/), which is appealing because, in theory, it allows for:
- front-loading most of the ops work so scaling happens automagically and no moving pieces for us to manage
- we can just tag new API endpoints on in discrete pieces as the project evolves
- it provides a sane path for changing APIs

(...or maybe none of that works as advertised and we'll end up building and deploy along more traditional lines)

**Comment by sashahart** [comment]
Sorry, I'm confused and I think I might have caused confusion by using the wrong words. Although I now appreciate this was unclear, by "data service" I was trying to talk about just the system which provides charting data to the frontend. I'll confess that my main interest was just in defining the interface that the frontend will use to consume charting data, analogous to the interface CartoDB will provide for consuming map layers. So I'd like either to discuss that charting API here, or split out a separate issue just for this API that supplies charting data (as opposed to say CartoDB which supplies map layers).

It sounds like you are willing to build the small API that your frontend will hit to get chart data. From my pipeline (#72) perspective, that API will solve this issue, so that all I need to know is what kind of data you want to have delivered where (#71) for the benefit of charting, in distinction from CartoDB map layers or other purposes.

If you are building the API then I don't at all care what pieces you use to do that, and I'm not going to second-guess your decisions on that.

**Comment by sashahart** [comment]
I don't think this issue has any purpose any more and I think it confuses matters, so I'm closing it.
